### ISSUE TITLE
我觉得一个断点就可以解决

### ISSUE THREAD

**Issue by XWJACK** [luoqisheng/lldb-symbolic#1]
<img width="456" alt="wx20181219-105056 2x" src="https://user-images.githubusercontent.com/15156226/50195935-28fce080-037c-11e9-9a78-e7876f8a7022.png">

**Comment by luoqisheng** [comment]
平时开发不是总开异常断点的 因为时常会在有异常处理的位置停住  由于异常断点并不是常开的 发生异常时 你可以重启打异常断点 这是我文中说的第一种处理方式  对于偶现问题 重启就失去了这个异常的现场
